### ISSUE TITLE
Unable to use google Auth

### ISSUE THREAD

**Issue by cmaspi** [iith-nss/iith_nss_jekyll#2]
![image](https://user-images.githubusercontent.com/69354325/191890277-fb287ef0-a166-4d80-84f2-6bce9a916f9f.png)

------
**How to Reproduce the error?**
use microsoft edge to access the portal

The error isn't limited to microsoft edge, I noticed the same issue on firefox

**Comment by Aayush2492** [comment]
Try going to https://nss.iith.ac.in/hours_portal instead of http://nss.iith.ac.in/hours_portal
